# vim: ts=2 sw=2 expandtab
definitions:
  - &main_db
    driver: 'sqlite'
    dsn: './data/stuff.sqlite'
data:
  menu: 'file://./data/menu.yml'
  stuff:
    type: 'sql'
    connection: *main_db
    query: 'SELECT title, body FROM stuff ORDER BY title'
rules:
- pattern: '/'
  data:
    files:
      type: 'dir'
      path: './data/pages'
      fetch: 4
      order: random
  template: 'home.html'
- pattern: '/stuff/{{id:*}}'
  data:
    page:
      type: 'sql'
      connection: *main_db
      query: 'SELECT title, body FROM stuff WHERE id = ?'
      params: [ "{{id}}" ]
      fetch: 'one'
  required:
    - page
  template: 'page.html'
- pattern: '/latest'
  data:
    files:
      type: 'dir'
      path: './data/pages'
      fetch: 10
      order: '-mtime'
  template: 'home.html'
- pattern: '/static/{{file:**}}'
  data:
    file: 'file://./static/{{file}}'
  static: true
- pattern: '/{{page:*}}'
  data:
    file: 'glob://./data/pages/{{page}}.*'
    page: 'file://./data/pages/{{page}}.*'
  required: [ 'page' ]
  template: 'page.html'
- pattern: '/{{page:*}}/json'
  data:
    page: 'file://./data/pages/{{page}}.*'
  required: [ 'page' ]
