# vim: ts=2 sw=2 expandtab
data:
  menu: 'file://./data/menu.yml'
  stuff:
    type: 'sql'
    dsn:
      driver: 'sqlite'
      dsn: './data/stuff.sqlite'
    query: 'SELECT title, body FROM stuff ORDER BY title'
rules:
- pattern: '/'
  data:
    files:
      type: 'dir'
      path: './data/pages'
      fetch: 4
      order: random
  template: 'home.html'
- pattern: '/latest'
  data:
    files:
      type: 'dir'
      path: './data/pages'
      fetch: 10
      order: '-mtime'
  template: 'home.html'
- pattern: '/static/{{file:**}}'
  data:
    file: 'file://./static/{{file}}'
  static: true
- pattern: '/{{page:*}}'
  data:
    file: 'glob://./data/pages/{{page}}.*'
    page: 'file://./data/pages/{{page}}.*'
  required: [ 'page' ]
  template: 'page.html'
- pattern: '/{{page:*}}/json'
  data:
    page: 'file://./data/pages/{{page}}.*'
  required: [ 'page' ]
