# vim: ts=2 sw=2 expandtab
Rules:
- pattern: '/'
  data:
    menu: 'file://./data/menu.yml'
    files: 'dir://./data/pages'
  template: 'home.html'
- pattern: '/static/{{file:**}}'
  data:
    file: 'file://./static/{{file}}'
  static: true
- pattern: '/{{page:*}}'
  data:
    menu: 'file://./data/menu.yml'
    page: 'file://./data/pages/{{page}}.*'
  required: [ 'page' ]
  template: 'page.html'
- pattern: '/{{page:*}}/json'
  data:
    menu: 'file://./data/menu.yml'
    page: 'file://./data/pages/{{page}}.*'
  required: [ 'page' ]
