# vim: ts=2 sw=2 expandtab
data:
  menu: 'file://./data/menu.yml'
backend-cache:
  - type: 'file'
    dir: '.cache'
  - 'file:.cache'
rules:
- pattern: '/'
  data:
    files:
      type: 'dir'
      path: './data/pages'
      fetch: 4
      order: random
  template: 'home.html'
- pattern: '/latest'
  data:
    files:
      type: 'dir'
      path: './data/pages'
      fetch: 10
      order: '-mtime'
  template: 'home.html'
- pattern: '/static/{{file:**}}'
  data:
    file: 'file://./static/{{file}}'
  static: true
- pattern: '/{{page:*}}'
  data:
    file: 'glob://./data/pages/{{page}}.*'
    page: 'file://./data/pages/{{page}}.*'
  required: [ 'page' ]
  template: 'page.html'
- pattern: '/{{page:*}}/json'
  data:
    page: 'file://./data/pages/{{page}}.*'
  required: [ 'page' ]
